version: "2"
services:
    php:
        build: ./
        container_name: web
        ports:
            - 4000:80
        links:
            - mysql
            - redis
        depends_on:
            - mysql
            - redis
        environment:
              - "DB_PORT=3306"
              - "DB_HOST=mysql"
        volumes:
              - .:/var/www
        command: >
            composer install --no-interaction --prefer-dist --optimize-autoloader
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=bilingua
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_USER=bilingua
            - MYSQL_PASSWORD=bilingua
        volumes:
            - ./storage/mysql:/var/lib/mysql
        ports:
            - 5306:3306
    redis:
        image: 'bitnami/redis:latest'
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        ports:
          - '9379:6379'
        volumes:
          - ./storage/redis:/bitnami
