<?php

namespace App\Controller\Admin;

use App\Controller\AdminController;
use Cake\Event\Event;

/**
 * FireExtinguisherCertificates Controller
 *
 * @property \App\Model\Table\FireExtinguisherCertificatesTable $FireExtinguisherCertificates
 *
 * @method \App\Model\Entity\FireExtinguisherCertificate paginate($object = null, array $settings = [])
 */
class FireExtinguisherCertificatesController extends AdminController
{

    public function beforeFilter(Event $event)
    {
       parent::beforeFilter($event); // TODO: Change the autogenerated stub
        //$this->set('menuId', 'FireExtinguisher');
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $fireExtinguisherCertificates = $this->paginate($this->FireExtinguisherCertificates);

        $this->set(compact('fireExtinguisherCertificates'));
        $this->set('_serialize', ['fireExtinguisherCertificates']);
    }

    /**
     * View method
     *
     * @param string|null $id Fire Extinguisher Certificate id.
     *
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $fireExtinguisherCertificate = $this->FireExtinguisherCertificates->get($id, [
            'contain' => [],
        ]);

        $this->set('fireExtinguisherCertificate', $fireExtinguisherCertificate);
        $this->set('_serialize', ['fireExtinguisherCertificate']);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $fireExtinguisherCertificate = $this->FireExtinguisherCertificates->newEntity();
        if ($this->request->is('post')) {
            $fireExtinguisherCertificate = $this->FireExtinguisherCertificates->patchEntity($fireExtinguisherCertificate, $this->request->getData());
            if ($this->FireExtinguisherCertificates->save($fireExtinguisherCertificate)) {
                $this->Flash->success(__('The fire extinguisher certificate has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The fire extinguisher certificate could not be saved. Please, try again.'));
        }
        $this->set(compact('fireExtinguisherCertificate'));
        $this->set('_serialize', ['fireExtinguisherCertificate']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Fire Extinguisher Certificate id.
     *
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $fireExtinguisherCertificate = $this->FireExtinguisherCertificates->get($id, [
            'contain' => [],
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $fireExtinguisherCertificate = $this->FireExtinguisherCertificates->patchEntity($fireExtinguisherCertificate, $this->request->getData());
            if ($this->FireExtinguisherCertificates->save($fireExtinguisherCertificate)) {
                $this->Flash->success(__('The fire extinguisher certificate has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The fire extinguisher certificate could not be saved. Please, try again.'));
        }
        $this->set(compact('fireExtinguisherCertificate'));
        $this->set('_serialize', ['fireExtinguisherCertificate']);
        $this->render('add');
    }

    /**
     * Delete method
     *
     * @param string|null $id Fire Extinguisher Certificate id.
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
//        $this->request->allowMethod(['post', 'delete']);
        $fireExtinguisherCertificate = $this->FireExtinguisherCertificates->get($id);
        if ($this->FireExtinguisherCertificates->delete($fireExtinguisherCertificate)) {
            $this->Flash->success(__('The fire extinguisher certificate has been deleted.'));
        } else {
            $this->Flash->error(__('The fire extinguisher certificate could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
